---
kind: Deployment
apiVersion: v1
metadata: 
    name:my-deployment
spec:
    replicas: 2
    strategy :
        type : Recreate
    selector: 
        matchLabels:
            app: my-app
    template:
        metadata:
            name: my-pod
            labels:
                app: my-app
        spec:
            containers:
            - image: Priti407/myimage
              name: mycontainer
              ports:
              - containerPort: 8501
... 
---
kind: Service
apiVersion :v1
metadata: 
    name:my-service
spec:
    type: NodePort
    selector:
        app: my-app
    Ports:
    - port: 80
      targetPort: 8501
      nodePort: 30001      
...                            